# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db8df23e40441f2ebac11b3a7eb7d596da877ff9509cb78ff2cbe856ff0d2705f2890c5af2d578f48ffe283ce103f09f6cf1aa1d8e5a135f4b38335c5e127240

test:
  secret_key_base: afe04c1200959e0b2eba4beab74d54dab383958da5cd9c6f7392fc57e53853da8cd6c7ba82d67c474072356f5916982af029dad3c51cf48a059c4ee0e2b1c42d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
